In [48]:
import pandas as pd
import matplotlib.pyplot as plt

In [49]:
df = pd.read_csv("messy_customer_sales_data.csv")

In [50]:
print(df)

      Customer_ID               Name  Gender         Age         City  \
0        CUST4371        Paul Wilson      m         52.0     KOLKATA
1        CUST5957       Jason Thomas       M  51.0 years          NaN
2        CUST3754  Brittney Martinez       F        62.0   hyderabad
3        CUST2934      Brenda Pierce  FEMALE        40.0   hyderabad
4        CUST5683    Matthew Carroll      f         41.0     CHENNAI
...           ...                ...     ...         ...          ...
10195   CUST10767       Robert Lewis  female  35.0 years       delhi
10196         NaN        Diane Evans       M        53.0   bangalore
10197    CUST6315    Joshua Martinez      m         25.0   hyderabad
10198    CUST4812       Sarah Miller  FEMALE        55.0          NaN
10199    CUST6588       David Potter  female        34.0   HYDERABAD

      Signup_Date Last_Purchase_Date  Purchase_Amount  Feedback_Score  \
0      2025-06-26         2025-05-17          26944.0             1.0
1      2021-02-17         2025-07-22          44152.0             2.0
2      2023-11-05         2024-12-08          31745.0             2.0
3      2022-03-13         2025-10-02          39674.0             1.0
4      2024-04-05         2024-12-15              NaN             8.0
...           ...                ...              ...             ...
10195  2020-12-08         2025-01-25          24167.0             9.0
10196  2023-12-31         2025-05-07          11639.0             7.0
10197  2022-02-15         2025-01-11          43832.0             2.0
10198  2021-03-16         2025-05-14          18827.0            10.0
10199  2020-10-12         2025-06-27          35211.0            10.0

                          Email  Phone_Number Country
0      peckvictoria@example.com    2131107701   India
1      owensanthony@example.com    1080761560   india
2            tara39@example.org    8981006345   India
3        berrynancy@example.org    8228064204   india
4          denise84@example.org    2665569480   India
...                         ...           ...     ...
10195    barrycrane@example.net    5004696571   InDia
10196    lisadennis@example.net    5200349941     IND
10197       kelli74@example.org    8147428496   India
10198        dawn84@example.org    2987564247   InDia
10199  kochjonathan@example.org    1926206725   India

[10200 rows x 12 columns]

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   str
 1   Name                10200 non-null  str
 2   Gender              9174 non-null   str
 3   Age                 9249 non-null   str
 4   City                9184 non-null   str
 5   Signup_Date         10200 non-null  str
 6   Last_Purchase_Date  9188 non-null   str
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  str
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   str
dtypes: float64(2), int64(1), str(9)
memory usage: 956.4 KB

In [52]:
df.describe().round(2)

       Purchase_Amount  Feedback_Score  Phone_Number
count          9179.00         9177.00  1.020000e+04
mean          29090.13            5.48  4.979974e+09
std          208697.09            2.87  2.902593e+09
min            -500.00            1.00  9.208990e+05
25%           12295.00            3.00  2.449157e+09
50%           24330.00            5.00  4.988639e+09
75%           37130.00            8.00  7.510448e+09
max         9999999.00           10.00  9.994402e+09

In [53]:
df.isnull().sum()/len(df)*100

Customer_ID           10.029412
Name                   0.000000
Gender                10.058824
Age                    9.323529
City                   9.960784
Signup_Date            0.000000
Last_Purchase_Date     9.921569
Purchase_Amount       10.009804
Feedback_Score        10.029412
Email                  0.000000
Phone_Number           0.000000
Country                7.176471
dtype: float64

In [54]:
df.shape

(10200, 12)

In [55]:
df.dropna().shape

(4528, 12)

In [56]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [57]:
df['Customer_ID'].value_counts().head(15)

Customer_ID
CUST6560     2
CUST7652     2
CUST6833     2
CUST6106     2
CUST8964     2
CUST10852    2
CUST10824    2
CUST5403     2
CUST8461     2
CUST4196     2
CUST10015    2
CUST10387    2
CUST6069     2
CUST6919     2
CUST10780    2
Name: count, dtype: int64

In [58]:
df[df['Customer_ID'] == 'CUST6560']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
96,CUST6560,Jeremy Wallace,NaN,NaN,DELHI,2022-01-09,2025-07-10,44888.0,2.0,stricklandalison@example.net,9233537609,NaN
3517,CUST6560,Jeremy Wallace,NaN,NaN,Delhi,2022-01-09,2025-07-10,44888.0,2.0,stricklandalison@example.net,9233537609,NaN

In [59]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(f"{col}: {df[col].unique()}")
        print("")

Gender: <StringArray>
['m ', 'M', 'F', 'FEMALE', 'f ', 'male', 'MALE', 'female', nan]
Length: 9, dtype: str

City: <StringArray>
[  ' KOLKATA ',           nan, ' hyderabad ',   ' CHENNAI ',   ' kolkata ',
 ' BANGALORE ', ' Hyderabad ', ' HYDERABAD ',    ' Mumbai ',   ' chennai ',
     ' Delhi ', ' bangalore ',    ' MUMBAI ', ' Bangalore ',   ' Kolkata ',
     ' delhi ',   ' Chennai ',    ' mumbai ',     ' DELHI ']
Length: 19, dtype: str

Feedback_Score: [ 1.  2.  8. 10.  3.  9. nan  4.  7.  5.  6.]

Country: <StringArray>
['India', 'india', nan, 'InDia', 'IND']
Length: 5, dtype: str

Handling Missing data

In [60]:
df.dropna(subset=['Customer_ID'], inplace=True)

In [61]:
print(df)

      Customer_ID               Name  Gender         Age         City  \
0        CUST4371        Paul Wilson      m         52.0     KOLKATA
1        CUST5957       Jason Thomas       M  51.0 years          NaN
2        CUST3754  Brittney Martinez       F        62.0   hyderabad
3        CUST2934      Brenda Pierce  FEMALE        40.0   hyderabad
4        CUST5683    Matthew Carroll      f         41.0     CHENNAI
...           ...                ...     ...         ...          ...
10194    CUST6146      Cody Thompson      f         40.0          NaN
10195   CUST10767       Robert Lewis  female  35.0 years       delhi
10197    CUST6315    Joshua Martinez      m         25.0   hyderabad
10198    CUST4812       Sarah Miller  FEMALE        55.0          NaN
10199    CUST6588       David Potter  female        34.0   HYDERABAD

      Signup_Date Last_Purchase_Date  Purchase_Amount  Feedback_Score  \
0      2025-06-26         2025-05-17          26944.0             1.0
1      2021-02-17         2025-07-22          44152.0             2.0
2      2023-11-05         2024-12-08          31745.0             2.0
3      2022-03-13         2025-10-02          39674.0             1.0
4      2024-04-05         2024-12-15              NaN             8.0
...           ...                ...              ...             ...
10194  2024-08-21         2024-10-26          35101.0             1.0
10195  2020-12-08         2025-01-25          24167.0             9.0
10197  2022-02-15         2025-01-11          43832.0             2.0
10198  2021-03-16         2025-05-14          18827.0            10.0
10199  2020-10-12         2025-06-27          35211.0            10.0

                            Email  Phone_Number Country
0        peckvictoria@example.com    2131107701   India
1        owensanthony@example.com    1080761560   india
2              tara39@example.org    8981006345   India
3          berrynancy@example.org    8228064204   india
4            denise84@example.org    2665569480   India
...                           ...           ...     ...
10194  mitchellrivera@example.net    6380823112   India
10195      barrycrane@example.net    5004696571   InDia
10197         kelli74@example.org    8147428496   India
10198          dawn84@example.org    2987564247   InDia
10199    kochjonathan@example.org    1926206725   India

[9177 rows x 12 columns]

In [62]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [63]:
df['Age'].unique()

<StringArray>
[      '52.0', '51.0 years',       '62.0',       '40.0',       '41.0',
          nan,       '18.0', '43.0 years', '40.0 years',       '26.0',
 ...
        '-10', '60.0 years', '24.0 years', '26.0 years', '21.0 years',
 '64.0 years', '50.0 years', '68.0 years', '32.0 years', '56.0 years']
Length: 109, dtype: str

In [64]:
print(df)

      Customer_ID               Name  Gender         Age         City  \
0        CUST4371        Paul Wilson      m         52.0     KOLKATA
1        CUST5957       Jason Thomas       M  51.0 years          NaN
2        CUST3754  Brittney Martinez       F        62.0   hyderabad
3        CUST2934      Brenda Pierce  FEMALE        40.0   hyderabad
4        CUST5683    Matthew Carroll      f         41.0     CHENNAI
...           ...                ...     ...         ...          ...
10194    CUST6146      Cody Thompson      f         40.0          NaN
10195   CUST10767       Robert Lewis  female  35.0 years       delhi
10197    CUST6315    Joshua Martinez      m         25.0   hyderabad
10198    CUST4812       Sarah Miller  FEMALE        55.0          NaN
10199    CUST6588       David Potter  female        34.0   HYDERABAD

      Signup_Date Last_Purchase_Date  Purchase_Amount  Feedback_Score  \
0      2025-06-26         2025-05-17          26944.0             1.0
1      2021-02-17         2025-07-22          44152.0             2.0
2      2023-11-05         2024-12-08          31745.0             2.0
3      2022-03-13         2025-10-02          39674.0             1.0
4      2024-04-05         2024-12-15              NaN             8.0
...           ...                ...              ...             ...
10194  2024-08-21         2024-10-26          35101.0             1.0
10195  2020-12-08         2025-01-25          24167.0             9.0
10197  2022-02-15         2025-01-11          43832.0             2.0
10198  2021-03-16         2025-05-14          18827.0            10.0
10199  2020-10-12         2025-06-27          35211.0            10.0

                            Email  Phone_Number Country
0        peckvictoria@example.com    2131107701   India
1        owensanthony@example.com    1080761560   india
2              tara39@example.org    8981006345   India
3          berrynancy@example.org    8228064204   india
4            denise84@example.org    2665569480   India
...                           ...           ...     ...
10194  mitchellrivera@example.net    6380823112   India
10195      barrycrane@example.net    5004696571   InDia
10197         kelli74@example.org    8147428496   India
10198          dawn84@example.org    2987564247   InDia
10199    kochjonathan@example.org    1926206725   India

[9177 rows x 12 columns]

In [65]:
import re
for i in df['Age'].apply(lambda x: re.sub(r'[^0-9]', '', str(x))):
    if len(i) <2:
        print(i)

def extract_age(age):
    age_num = re.findall('[0-9]+', str(age))
    if len(age_num) > 0:
        return age_num[0]
    else:
        return age

df['Age'] = df['Age'].apply(lambda x: extract_age(x))

3






































































































































































































































3





























































































































































































3



































































































































































3























































































































3

In [66]:
df_age = df[df['Age'] != 'nan years']['Age']

In [67]:
df_age

0        52
1        51
2        62
3        40
4        41
         ..
10194    40
10195    35
10197    25
10198    55
10199    34
Name: Age, Length: 9120, dtype: str

In [68]:
age_median = int(df_age.dropna().astype('int64').median())

In [69]:
age_median

43

In [70]:
df.replace('nan years', age_median, inplace=True)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,f,40,NaN,2024-08-21,2024-10-26,35101.0,1.0,mitchellrivera@example.net,6380823112,India
10195,CUST10767,Robert Lewis,female,35,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10197,CUST6315,Joshua Martinez,m,25,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [71]:
df['Age'].fillna(age_median, inplace=True)

C:\Users\soyam\AppData\Local\Temp\ipykernel_21056\2877544036.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(age_median, inplace=True)

0        52
1        51
2        62
3        40
4        41
         ..
10194    40
10195    35
10197    25
10198    55
10199    34
Name: Age, Length: 9177, dtype: object

In [72]:
df['Age'].unique()

array(['52', '51', '62', '40', '41', nan, '18', '43', '26', '32', '22',
       '59', '65', '61', '31', '54', '55', '69', '24', '63', '19', '50',
       '56', '36', '68', '38', '27', '57', '23', '25', '66', '28', '30',
       '46', '48', '20', '37', '67', '35', '58', '29', 43, '39', '49',
       '47', '42', '44', '64', '53', '60', '45', '21', '34', '33', '250',
       '3', '10'], dtype=object)

In [73]:
df['Purchase_Amount'].fillna(df['Purchase_Amount'].median(), inplace=True)

C:\Users\soyam\AppData\Local\Temp\ipykernel_21056\2911039778.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Purchase_Amount'].fillna(df['Purchase_Amount'].median(), inplace=True)

0        26944.0
1        44152.0
2        31745.0
3        39674.0
4        24268.0
          ...
10194    35101.0
10195    24167.0
10197    43832.0
10198    18827.0
10199    35211.0
Name: Purchase_Amount, Length: 9177, dtype: float64

In [74]:
df = pd.read_csv("messy_customer_sales_data.csv")
df.dropna(subset=['Customer_ID'], inplace=True)

df['Age'] = df['Age'].replace('nan years', age_median)
df['Age'] = df['Age'].fillna(age_median)

df['Purchase_Amount'] = df['Purchase_Amount'].fillna(df['Purchase_Amount'].median())
df['Feedback_Score'] = df['Feedback_Score'].fillna(df['Feedback_Score'].mode().iloc[0])

print(df.isnull().sum())

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score          0
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [75]:
for col in ['Gender', 'City', 'Country']:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\soyam\AppData\Local\Temp\ipykernel_21056\2616801518.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].mode()[0], inplace=True)

In [76]:
df['Last_Purchase_Date'].fillna(df['Last_Purchase_Date'].mode()[0], inplace=True)

C:\Users\soyam\AppData\Local\Temp\ipykernel_21056\2401474567.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Last_Purchase_Date'].fillna(df['Last_Purchase_Date'].mode()[0], inplace=True)

0        2025-05-17
1        2025-07-22
2        2024-12-08
3        2025-10-02
4        2024-12-15
            ...
10194    2024-10-26
10195    2025-01-25
10197    2025-01-11
10198    2025-05-14
10199    2025-06-27
Name: Last_Purchase_Date, Length: 9177, dtype: str

FIXING INCONSISTENT FORMATTING

In [77]:
df['Gender'].unique()

<StringArray>
['m ', 'M', 'F', 'FEMALE', 'f ', 'male', 'MALE', 'female', nan]
Length: 9, dtype: str

In [78]:
df['Gender'] = df['Gender'].str.lower().str.strip()
df['Gender'] = df['Gender'].replace({'m': 'male', 'f': 'female'})

In [79]:
df['Gender'].unique()

<StringArray>
['male', 'female', nan]
Length: 3, dtype: str

In [80]:
df['City'].unique()

<StringArray>
[  ' KOLKATA ',           nan, ' hyderabad ',   ' CHENNAI ',   ' kolkata ',
 ' BANGALORE ', ' Hyderabad ', ' HYDERABAD ',    ' Mumbai ',   ' chennai ',
     ' Delhi ', ' bangalore ', ' Bangalore ',   ' Kolkata ',     ' delhi ',
   ' Chennai ',    ' MUMBAI ',     ' DELHI ',    ' mumbai ']
Length: 19, dtype: str

In [81]:
df['City'] = df['City'].str.strip().str.lower()

In [82]:
df['Country'] = df['Country'].str.strip().str.lower()

In [83]:
df['Country'].replace({'ind': 'india'}, inplace=True)

C:\Users\soyam\AppData\Local\Temp\ipykernel_21056\1774004472.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Country'].replace({'ind': 'india'}, inplace=True)

0        india
1        india
2        india
3        india
4        india
         ...
10194    india
10195    india
10197    india
10198    india
10199    india
Name: Country, Length: 9177, dtype: str

Handling Duplicates Records

In [84]:
df[df.duplicated()].shape

(128, 12)

In [85]:
df.drop_duplicates(inplace=True)

In [86]:
df[df.duplicated()].shape

(0, 12)

In [87]:
df['Customer_ID'].value_counts()

Customer_ID
CUST7652     2
CUST6833     2
CUST10852    2
CUST8461     2
CUST10387    2
            ..
CUST6352     1
CUST6146     1
CUST10767    1
CUST6315     1
CUST4812     1
Name: count, Length: 9000, dtype: int64

In [88]:
df[df['Customer_ID'] == 'CUST9534']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
3528,CUST9534,Melissa Jones,male,53.0,NaN,2021-08-26,NaN,21959.0,8.0,cassandrahill@example.net,7734467854,india

In [89]:
df.drop_duplicates(subset=['Customer_ID'], keep='first', inplace=True)

In [90]:
df[df['Customer_ID'] == 'CUST9534']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
3528,CUST9534,Melissa Jones,male,53.0,NaN,2021-08-26,NaN,21959.0,8.0,cassandrahill@example.net,7734467854,india

Correcting Data Types

In [91]:
df.dtypes

Customer_ID               str
Name                      str
Gender                    str
Age                    object
City                      str
Signup_Date               str
Last_Purchase_Date        str
Purchase_Amount       float64
Feedback_Score        float64
Email                     str
Phone_Number            int64
Country                   str
dtype: object

In [92]:
df['Age']

0              52.0
1        51.0 years
2              62.0
3              40.0
4              41.0
            ...
10193          26.0
10194          40.0
10195    35.0 years
10197          25.0
10198          55.0
Name: Age, Length: 9000, dtype: object

In [93]:
df['Age'] = df['Age'].astype('int64')

ValueError: invalid literal for int() with base 10: '52.0'

In [94]:
df['Age']

0              52.0
1        51.0 years
2              62.0
3              40.0
4              41.0
            ...
10193          26.0
10194          40.0
10195    35.0 years
10197          25.0
10198          55.0
Name: Age, Length: 9000, dtype: object

In [95]:
df.columns

Index(['Customer_ID', 'Name', 'Gender', 'Age', 'City', 'Signup_Date',
       'Last_Purchase_Date', 'Purchase_Amount', 'Feedback_Score', 'Email',
       'Phone_Number', 'Country'],
      dtype='str')

In [96]:
df['Signup_Date'] = pd.to_datetime(df['Signup_Date'])

In [97]:
df['Last_Purchase_Date'] = pd.to_datetime(df['Last_Purchase_Date'])

In [ ]:
df.dtypes

In [ ]:
cols = ['Customer_ID', 'Name', 'Gender', 'City', 'Email']
df[cols] = df[cols].astype('object')

In [ ]:
df.dtypes

Handling outliers

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

cols  = ['Age', 'Purchase_Amount', 'Feedback_Score']
plt.figure(figsize=(15,5))

for i, col in enumerate(cols, 1):
    plt.subplot(1,3,i)
    sns.boxplot(y = df[col], color = 'skyblue', width = 0.3)
    plt.title(f'{col} boxplot', fontsize = 15)
    plt.ylabel('')
    plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

In [ ]:
from scipy import stats

In [ ]:
import numpy as np

In [ ]:
z_scores = np.abs(stats.zscore(df[['Age', 'Purchase_Amount']]))
abs_z_scores = abs(z_scores)

In [ ]:
df_clean = df[~(z_scores > 3).any(axis=1)]

In [ ]:
df_clean.shape

In [ ]:
df